USE [master]
GO

/****** Object:  Database [ShopEverythingForRepair]    Script Date: 06.04.2023 14:10:07 ******/
CREATE DATABASE [ShopEverythingForRepair]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ShopEverythingForRepair', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ShopEverythingForRepair.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ShopEverythingForRepair_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ShopEverythingForRepair_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ShopEverythingForRepair].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ShopEverythingForRepair] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ShopEverythingForRepair] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ShopEverythingForRepair] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ShopEverythingForRepair] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ShopEverythingForRepair] SET ARITHABORT OFF 
GO

ALTER DATABASE [ShopEverythingForRepair] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ShopEverythingForRepair] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ShopEverythingForRepair] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ShopEverythingForRepair] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ShopEverythingForRepair] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ShopEverythingForRepair] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ShopEverythingForRepair] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ShopEverythingForRepair] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ShopEverythingForRepair] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ShopEverythingForRepair] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ShopEverythingForRepair] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ShopEverythingForRepair] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ShopEverythingForRepair] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ShopEverythingForRepair] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ShopEverythingForRepair] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ShopEverythingForRepair] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ShopEverythingForRepair] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ShopEverythingForRepair] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ShopEverythingForRepair] SET  MULTI_USER 
GO

ALTER DATABASE [ShopEverythingForRepair] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ShopEverythingForRepair] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ShopEverythingForRepair] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ShopEverythingForRepair] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ShopEverythingForRepair] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ShopEverythingForRepair] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ShopEverythingForRepair] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ShopEverythingForRepair] SET  READ_WRITE 
GO

